[build]
  command = "node scripts/netlify-build.cjs"
  publish = "dist"
  ignore = "/bin/false"

[build.environment]
  NODE_VERSION = "20.15.1"
  NPM_VERSION = "10"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NODE_OPTIONS = "--max-old-space-size=8192"
  SKIP_PREFLIGHT_CHECK = "true"
  CI = "true"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  # NODE_ENV = "production" # Commented out to ensure devDependencies are installed

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
