[build]
  command = "node --version && npm --version && npm run build:netlify"
  publish = "dist"
  base = ""

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  NPM_CONFIG_OPTIONAL = "true"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NETLIFY_USE_YARN = "false"

[context.production]
  command = "node --version && npm --version && npm run build:netlify"
  
[context.deploy-preview]
  command = "node --version && npm --version && npm run build:netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"