[build]
  command = "rm -rf node_modules package-lock.json && npm install --include=optional --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "9.0.0"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_OPTIONAL = "true"
  SKIP_PREFLIGHT_CHECK = "true"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
