import { HvacEntry } from '../types';

const rawHvacData = `Building	Main System	Equipment	PPM1 Findings	PPM2 Findings	PPM3 Findings	PPM4 Findings	Common Issues	Fixed Issues	Notes	Actions
CIF	York Chiller	Chiller #1 (Sys #1 & #2)	Water sensor inlet (1); Plug sensor (1); Plug transducer (1)	Water sensor inlet (1) (Need LPO); Plug sensor (1) (Need LPO); Plug transducer (1) (Need LPO)	Water Sensor Inlet Defective (1); Plug Sensor Defective (2); Plug Transducer Defective (2)	Water Sensor Inlet Defective Need To Replace (1); Plug Sensor Defective Need To Replace (2); Educator Sensor Defective Need To Replace (1); Plug Transducer Defective Need To Replace (2)	Water sensor inlet, plug sensor, plug transducer	None	Quantities adjusted between PPM1 and PPM2; PPM3/PPM4 show continued issues requiring replacement	
FM	York Chiller	Chiller #1	Fuse 3A (3); Fuse 20A (6); Water sensor (2); Plug sensor (2); Plug transducer (2); Flow switch (1); Leak test; Solenoid valve (1); Insulation	Fuse 3A (3), Fuse 20A (6), Water sensor (2), Plug sensor (2), Plug transducer (2), Flow switch (1), Leak test (1), Solenoid valve (1), Insulation (1) (all Need LPO). Also: R410A (2), N2 (1), Filter (1), Pump bearing (1), Check valve (1) (Need LPO)	Water Sensor Defective Need To Replace (2); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Power Main Switch Defective Need To Replace (1); Water Pressure Gauge Defective Need To Replace (1); Condenser Fan Motor Make Noise Need To Bearing Replacement (1); Pump Making Noise Need To Bearing Replacement And Check The Valve (1); Pump Need Overhauling (1)	Water Sensor Defective Need To Replace (2); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Power Main Switch Defective Need To Replace (1); Water Pressure Gauge Defective Need To Replace (1); Condenser Fan Motor Make Noise Need To Bearing Replacement (1); Pump Making Noise Need To Bearing Replacement And Check The Valve (1); Pump Need Overhauling (1)	Fuses, water sensor, plug sensor, plug transducer, flow switch, leak test, solenoid valve, insulation	None	Multiple mechanical issues identified in PPM3/PPM4 including pump overhaul requirements	
FM	York Chiller	Chiller #2			Pump No.1 Need Overhauling (1); Pump No.2 Need Overhauling (1); Water Sensor Inlet Defective Need To Replace (1); Exv Defective Need To Replace (1); Condenser Fan Motor Make Noise Need To Bearing Replacement (2)	Pump No.1 Need Overhauling (1); Pump No.2 Need Overhauling (1); Water Sensor Inlet Defective Need To Replace (1); Exv Defective Need To Replace (1); Condenser Fan Motor Make Noise Need To Bearing Replacement (2)			Equipment identified in PPM3/PPM4 visits - not in original tracker	
FM	Pressurisations	Pressurization Unit No.2			High Pressure Cut Out Need to Replace (1); Switch Pressure Cut Out Need To Replace (1); Need Bearing Replacement (1)	High Pressure Cut Out Need to Replace (1); Switch Pressure Cut Out Need To Replace (1); Need Bearing Replacement (1)			Equipment identified in PPM3/PPM4 visits - not in original tracker	
B1	York Chiller	Pressurization Unit #3	High-pressure cut-out (1)	High-Pressure Cut-Out (1) → DONE (per contractor); Valve 1" (4) (Need LPO)	High Pressure Cut Out Need to Replace (1); Need Change Valve 1 Inch (4)	High Pressure Cut Out Need to Replace (1); Need Change Valve 1 Inch (4)	High-pressure cut-out (1)	None	Contractor separately listed "PRESSURE SWITCH (1) DONE," likely the same as High-Pressure Cut-Out. Valves (4) are new in PPM2 but not yet installed (Need LPO)	
B1	York Chiller	Chiller #1 (Sys #1 & #2)	Transformer (1); 12A fuse (1); 20A fuses (6); Plug sensor (2); Plug transducer (2); Flow switch (1); Water sensor (2); Insulation; Leak test	Carried Over (Need LPO): Transformer (1), 12A fuse (1), 20A fuses (6), Plug sensor (2), Plug transducer (2), Flow switch (1), Water sensor (2), Insulation, Leak test, Solenoid valve (1) (new from earlier PPM2) Also from contractor: R410A (2), N2 (1), Filter (1) (Need LPO) (Consumables for refilling system.)	Before Check The Chiller Then Transformer Need Replace (1); Fuse Defective Need To Replace (1); Fuse Defective Need To Replace (6); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Need To Leak Test (1); Solenoid Valve Defective Need To Replace (1); Inlet And Outlet Water Pipe Need Insulation (1); Flow Switch Defective Need To Replace (1); Water Sensor Inlet Defective Need To Replace (2)	Before Check The Chiller Then Transformer Need Replace (1); Fuse Defective Need To Replace (1); Fuse Defective Need To Replace (6); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Need To Leak Test (1); Solenoid Valve Defective Need To Replace (1); Inlet And Outlet Water Pipe Need Insulation (1); Water Sensor Inlet Defective Need To Replace (2)	Transformer (1), 12A fuse (1), 20A fuses (6), plug sensor (2), plug transducer (2), flow switch (1), water sensor (2), insulation, leak test	None	Contractor explicitly added "R410A(2), N2(1), filter(1)" as new consumables. All main PPM1 items remain open (Need LPO). Solenoid valve was introduced in earlier PPM2 data and still needs replacement	
B1	York Chiller	Chiller #2	Plug sensor (1); Fuse (1); Flow switch (1)	Plug sensor (2) (Need LPO), Plug transducer (2) (Need LPO), Flow switch (1) (Need LPO), Water temp. sensor (1) (Need LPO), Leak test (1) (Need LPO), (Fuse from PPM1 not repeated) Also: R410A (2), N2 (1), Filter (1) (Need LPO)	Flow Switch Defective Need To Replace (1); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Water Temperature Sensor Inlet Defective Need To Replace (1); Need To Leak Test (1)	Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Water Temperature Sensor Inlet Defective Need To Replace (1); Need To Leak Test (1)	Plug sensor (common item; quantity discrepancy: PPM1=1 vs. PPM2=2), Flow switch (1)		Plug transducer(2) & water temp sensor(1) are new in PPM2. The missing fuse implies it was likely fixed. Additional consumables (R410A, N2, filter) per contractor	
B2	Pressurisations	Pressurization Unit #3	High-pressure cut-out (1)	High-Pressure Cut Out (1) (Need LPO)			High-pressure cut-out (1)	None	No other PPM2 additions for this unit	
B2	York Chiller	Chiller #1 (Sys #1 & #2)	12A Fuse (1); 20A Fuses (6); Leak test; Cooler insulation; Plug sensor (2); Plug transducer (2); Flow switch (1); Water sensor (2)	12A Fuse (1), 20A Fuses (6), Leak test (1), New Cooler (1), Cooler Insulation (1), Plug sensor (2), Plug transducer (2), Flow switch (1), Water sensor (2) (all Need LPO). Contractor also lists: R410A (4), N2 (1), Filter(s) (1), "Chell Filter"(1), "Core Filter"(2), Oil 32 RLH 1 GAL(2), Control Transformer 24V(1), Fuse KIT/Transducer/Sensor connectors(1) (Need LPO). Some items installed but "Need extra items" for final completion	Fuse Defective Need To Replace (1); Flow Switch Defective Need To Replace (1); Need To Leak Test (1); Cooler Insulation (1); Water Sensor Defective Need To Replace (2); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Fuse Defective Need To Replace (6)	Fuse Defective Need To Replace (1); Need To Leak Test (1); Cooler Insulation (1); Water Sensor Defective Need To Replace (2); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Fuse Defective Need To Replace (6)	12A fuse, 20A fuses, leak test, cooler insulation, plug sensor(2), plug transducer(2), flow switch(1), water sensor(2)	None	Extensive additional consumables required	
B2	York Chiller	Chiller #1 Sys#2			Plug Sensor Defective (2); Plug Transducer Defective (2); Flow Switch Defective (1)	Need To Leak Test (1); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2)			Equipment identified in PPM3/PPM4 visits - not in original tracker	
B2	Pressurisations	Pressurization Unit #4	High-pressure cut-out (1)	High-Pressure Cut Out (1) (Need LPO)	High Pressure Cut Out (1)	High Pressure Cut Out Need to Replace (1)	High-pressure cut-out (1)	None	No other PPM2 additions for this unit	
B3	York Chiller	Chiller #1	Flow switch (1); On/off switch (1)	Flow switch (1) (Need LPO); On/off switch (1) (Need LPO)	Flow Switch Defective Need To Replace (1); On/Off Switch Defective Need To Replace (1)	On/Off Switch Defective Need To Replace (1)	Flow switch, on/off switch	None	No other PPM2 additions for this chiller	
B3	York Chiller	Chiller #2			Flow Switch Defective (1); Plug Sensor Defective (2); Plug Transducer Defective (2); On/Off Switch Defective (1)	Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); On/Off Switch Defective Need To Replace (1)			Equipment identified in PPM3/PPM4 visits - not in original tracker	
B4	York Chiller	Chiller #1	Plug sensor (1); Plug transducer (1); Flow switch (1)	Plug sensor (1) (Need LPO), Plug transducer (1) (Need LPO), Flow switch (1) (Need LPO)	Flow Switch Defective (1); Plug Sensor Defective (2); Plug Transducer Defective (2)	Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2)	Plug sensor, plug transducer, flow switch	None	No other PPM2 additions for this chiller	
B4	York Chiller	Chiller #2	Plug sensor (1); Plug transducer (1); Flow switch (1)	Plug sensor (1) (Need LPO), Plug transducer (1) (Need LPO), Flow switch (1) (Need LPO)	Plug Sensor Defective (2); Plug Transducer Defective (2); Flow Switch Defective (1)	Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2)	Plug sensor, plug transducer, flow switch	None	No other PPM2 additions for this chiller	
B4	Pressurisations	Pressurization Unit No.6				Switch Pressure Cut Out Need To Replace (1); Pump Need Paint (1)			Equipment identified in PPM3/PPM4 visits - not in original tracker	
B4	Pressurisations	Pressurization Unit #4						None		
B5	York Chiller	Chiller #1	Fuse 12A (1); Fuse 20A (6); Water sensor (2); Plug sensor (2); Plug transducer (2); Flow switch (1); Leak test; New cooler (1)	Fuse 12A (1), Fuse 20A (6), Water sensor (2), Plug sensor (2), Plug transducer (2), Flow switch (1), Leak test (1), New cooler (1) (all Need LPO). Additional items: R410A (4), N2 (1), Filters (1), "Chell Filter"(1), "Core Filter"(2), Oil 32 RLH 1 GAL(2) (Need LPO)	Flow Switch Defective Need To Replace (1); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Fuse Defective Need To Replace (1); Fuse Defective Need To Replace (6); Water Sensor Defective Need To Replace (2); New Cooler Need to Replace (1); Need To Leak Test (1)	Flow Switch Defective Need To Replace (1); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Fuse Defective Need To Replace (1); Fuse Defective Need To Replace (6); Water Sensor Defective Need To Replace (2); New Cooler Need to Replace (1); Need To Leak Test (1)	Fuse 12A, fuse 20A, water sensor, plug sensor, plug transducer, flow switch, leak test, new cooler	None	Additional consumables added in PPM2: R410A, N2, filters, oil	
B5	York Chiller	Chiller #2	Flow switch (1); On/off switch (1)	Flow switch (1) (Need LPO); On/off switch (1) (Need LPO)	Flow Switch Defective Need To Replace (1); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); On/Off Switch Defective Need To Replace (1)	Flow Switch Defective Need To Replace (1); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); On/Off Switch Defective Need To Replace (1)	Flow switch, on/off switch	None	No other PPM2 additions for this chiller	
B5	York Chiller	Chiller#1 Sys#2			Need To Leak Test (1)	Need To Leak Test (1)			Equipment identified in PPM3/PPM4 visits - not in original tracker	
B5	York Chiller	Chiller#2 Sys#2			Need To Leak Test (1)	Need To Leak Test (1)			Equipment identified in PPM3/PPM4 visits - not in original tracker	
B5	Pressurisations	Pressurization Unit #7	High-pressure cut-out (1)	High-Pressure Cut Out (1) (Need LPO)	High Pressure Cut Out Need to Replace (1)	High Pressure Cut Out Need to Replace (1)	High-pressure cut-out (1)	None	No other PPM2 additions for this unit	
B6	York Chiller	Chiller #1	Plug sensor (2); Plug transducer (2); Flow switch (1)	Plug sensor (2) (Need LPO), Plug transducer (2) (Need LPO), Flow switch (1) (Need LPO)	Condenser Fan Motor Make Noise Need To Bearing Replacement (4); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Flow Switch Defective Need To Replace (1)	Condenser Fan Motor Make Noise Need To Bearing Replacement (4); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2)	Plug sensor, plug transducer, flow switch	None	No other PPM2 additions for this chiller	
B6	York Chiller	Chiller #2	Plug sensor (2); Plug transducer (2); Flow switch (1)	Plug sensor (2) (Need LPO), Plug transducer (2) (Need LPO), Flow switch (1) (Need LPO)	Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Flow Switch Defective Need To Replace (1)	Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2)	Plug sensor, plug transducer, flow switch	None	No other PPM2 additions for this chiller	
B6	Pressurisations	Pressurization Unit #8	Switch pressure cut-out (1)	Switch Pressure Cut Out (1) (Need LPO)	Switch Pressure Cut Out Need To Replace (1)	Switch Pressure Cut Out Need To Replace (1)	Switch pressure cut-out (1)	None	No other PPM2 additions for this unit	
B7	York Chiller	Chiller #1 (Sys #1)	Plug sensor (2); Plug transducer (2); Flow switch (1)	Plug sensor (2) (Need LPO), Plug transducer (2) (Need LPO), Flow switch (1) (Need LPO)	Condenser Fan Motor Make Noise Need To Bearing Replacement (2); Plug Sensor Defective Need To Replace (2); Flow Switch Defective Need To Replace (1); Plug Transducer Defective Need To Replace (2)	Condenser Fan Motor Make Noise Need To Bearing Replacement (2); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2)	Plug sensor, plug transducer, flow switch	None	No other PPM2 additions for this chiller	
B7	York Chiller	Chiller #2 (Sys #1 & #2)	Fuse 3A (3); Water pump bearing (1); Plug sensor (2); Plug transducer (2); Flow switch (1); Leak test	Fuse 3A (3) (Need LPO), Water pump bearing (1) (Need LPO), Plug sensor (2) (Need LPO), Plug transducer (2) (Need LPO), Flow switch (1) (Need LPO), Leak test (1) (Need LPO). Additional consumables: R410A (2), N2 (1), Filter (1) (Need LPO)	Fuse Defective Need To Replace (3); Water Pump Need Bearing Change (1); Plug Sensor Defective Need To Replace (2); Need To Leak Test (1); Plug Transducer Defective Need To Replace (2); Flow Switch Defective Need To Replace (1)	Fuse Defective Need To Replace (3); Water Pump Need Bearing Change (1); Plug Sensor Defective Need To Replace (2); Need To Leak Test (1); Plug Transducer Defective Need To Replace (2)	Fuse 3A, water pump bearing, plug sensor, plug transducer, flow switch, leak test	None	Contractor added consumables: R410A(2), N2(1), filter(1)	
B7	York Chiller	Chiller#1 Sys #2			Condenser Fan Contactor Defective Need To Replace (2); Fan Motor Defective Need To Rewinding (1); Required Leak Test (1); Fuse Defective Need To Replace (3); Water Pump Need Bearing Change (1)	Condenser Fan Contactor Defective Need To Replace (2); Fan Motor Defective Need To Rewinding (1); Required Leak Test (1); Fuse Defective Need To Replace (3); Water Pump Need Bearing Change (1)			Equipment identified in PPM3/PPM4 visits - not in original tracker	
B7	Pressurisations	Pressurization Unit #2	Switch pressure cut-out (1); Valve 1" (4); Bearing replacement	Switch pressure cut-out (1) (Need LPO); Valve 1" (4) (Need LPO); Bearing replacement (1) (Need LPO)			Switch pressure cut-out, valve 1", bearing replacement	None	No other changes in PPM2	
B7	Pressurisations	Pressurization Unit No.9			Need Change Start Control Hand Sit (1); Switch Pressure Cut Out Need To Replace (1); Need Change Valve 1 Inch (4)	Need Change Start Control Hand Sit (1); Switch Pressure Cut Out Need To Replace (1); Need Change Valve 1 Inch (4)			Equipment identified in PPM3/PPM4 visits - not in original tracker	
B8	(All)	(Misc. Water Chemical Treatment)	Chemical treatment (Need LPO)	Chemical treatment (1) (Need LPO)			Chemical treatment	None	Water chemical treatment required across all equipment	
B8	York Chiller	Chiller #1 (Sys #1 & #2)	Fuse (1); Suction transducer (1); Plug sensor (2); Plug transducer (2); Flow switch (1); Pump overhaul (1); Leak test	Fuse (1) (Need LPO), Suction transducer (1) (Need LPO), Plug sensor (2) (Need LPO), Plug transducer (2) (Need LPO), Flow switch (1) (Need LPO), Pump overhaul (1) (Need LPO), Leak test (1) (Need LPO). Additional: R410A (2), N2 (1), Filter (1) (Need LPO)	There Is No Gas (1); Pump No.1 Need Overhauling (1); Suction Transducer Defective (1); Plug Sensor Defective (2); Plug Transducer Defective (2); Flow Switch Defective (1)	There Is No Gas Need To Leak Test (1); Pump No.1 Need Overhauling (1); Suction Transducer Defective Need To Replace (1); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2)	Fuse, suction transducer, plug sensor, plug transducer, flow switch, pump overhaul, leak test	None	Critical issue: no refrigerant gas detected. Additional consumables: R410A(2), N2(1), filter(1)	
B8	York Chiller	Chiller #2 (Sys #1 & #2)	Suction transducer (1); Discharge transducer (1); Filter drier holder (1); Plug sensor (2); Plug transducer (2); Condenser fan bearing (1); Pump overhaul (1); Water sensor inlet (1); Fuse (1)	Suction transducer (1) (Need LPO), Discharge transducer (1) (Need LPO), Filter drier holder (1) (Need LPO), Plug sensor (2) (Need LPO), Plug transducer (2) (Need LPO), Condenser fan bearing (1) (Need LPO), Pump overhaul (1) (Need LPO), Water sensor inlet (1) (Need LPO), Fuse (1) (Need LPO). Additional: R410A (2), N2 (1), Filter (1) (Need LPO)	There Is No Gas (1); Suction Transducer Defective (1); Discharge Transducer Defective (1); Change The Filter Drier Holder (1); Plug Sensor Defective (2); Plug Transducer Defective (2); Condenser Fan Need Bearing (1); Pump No.2 Need Overhauling (1); Water Sensor Inlet Defective (1); Fuse Defective (1); Condenser Fan Need Bearing Replacement (1); Fuse Defective Need To Replace (1); Flow Switch Defective Need To Replace (1)	There Is No Gas Need To Leak Test (1); Suction Transducer Defective Need To Replace (1); Discharge Transducer Defective Need To Replace (1); Change The Filter Drier Holder (1); Plug Sensor Defective Need To Replace (2); Plug Transducer Defective Need To Replace (2); Condenser Fan Need Bearing Replacement (1); Pump No.2 Need Overhauling (1); Water Sensor Inlet Defective Need To Replace (1); Fuse Defective Need To Replace (1); Fuse Defective Need To Replace (1); Condenser Fan Need Bearing Replacement (1)	Suction transducer, discharge transducer, filter drier holder, plug sensor, plug transducer, condenser fan bearing, pump overhaul, water sensor inlet, fuse	None	Critical issue: no refrigerant gas detected. Comprehensive repairs needed. Additional consumables: R410A(2), N2(1), filter(1)	
B8	Pressurisations	Pressurization Unit #10	High-pressure cut-out (1); Pipe connector (1)	High-Pressure Cut Out (1) (Need LPO); Pipe connector for pump (1) (Need LPO)	High Pressure Cut Out (1); Pipe Connector For Pump Need (1)	High Pressure Cut Out Need to Replace (1)	High-pressure cut-out, pipe connector	None	New pipe connector identified in PPM2	
`;

export const parseHvacData = (data: string): HvacEntry[] => {
    const lines = data.trim().split('\n').slice(1);
    
    return lines.map((line, index) => {
        const values = line.split('\t');
        return {
            id: `${values[0]?.trim()}-${values[2]?.trim()}-${index}`,
            building: values[0]?.trim() || '',
            mainSystem: values[1]?.trim() || '',
            equipment: values[2]?.trim() || '',
            ppm1Findings: values[3]?.trim() || '',
            ppm2Findings: values[4]?.trim() || '',
            ppm3Findings: values[5]?.trim() || '',
            ppm4Findings: values[6]?.trim() || '',
            commonIssues: values[7]?.trim() || '',
            fixedIssues: values[8]?.trim() || '',
            notes: values[9]?.trim() || '',
        };
    });
};

export const hvacData = parseHvacData(rawHvacData);
